### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by ricir** [noroot/jekyll-mail-comments#2]
Hi Dmitry,

I ask a little help for running the plugin.

I tried to run this jekyll plugin  (I had a look to **isso** but its installation seems to need a little bit more requirements).

- I installed the gem.
- I configured .env.dist under **jekyll-mail-comments-0.0.2**  in the gems folder with imap, port, userid and password of my mail account. - (Pls note that I did not choose a gmail account because I do not know if  their auth method allows this  simple imap access.)
- I sent an e-mail containing jekyll in the subject to my address specified in. env.dist. 
- I created a _data folder under the folder of my local jekyll site.

When I run jekyll-mail-comments-fetch from a console in the folder of my local jekyll site I receive the following:
```

Traceback (most recent call last):
	7: from /home/ricir/gems/bin/jekyll-mail-comments-fetch:23:in `<main>'
	6: from /home/ricir/gems/bin/jekyll-mail-comments-fetch:23:in `load'
	5: from /home/ricir/gems/gems/jekyll-mail-comments-0.0.2/bin/jekyll-mail-comments-fetch:3:in `<top (required)>'
	4: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	3: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	2: from /home/ricir/gems/gems/jekyll-mail-comments-0.0.2/lib/jekyll-mail-comments.rb:2:in `<top (required)>'
	1: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- mail (LoadError)
```

**Comment by ricir** [comment]
> /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- mail (LoadError)
> ```

I solved the issue by manually installing mail gem.

**Comment by noroot** [comment]
Good, but it is in the `Gemfile` already, you probably need to run `bundle install` to install dependencies.
